- name: Install Docker Engine
  hosts: ci-server
  gather_facts: false
  become: true

  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: false

  tasks:
    - name: Install packages to allow apt to use a repository over HTTPS 
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      tags: docker   

    - name: Add docker repository key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: docker

    - name: Set up docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu xenial stable
        state: present
      tags: docker

    - name: Install docker
      apt: 
        name: "{{ item }}"
      with_items:
        - docker-ce
        - docker-compose
      tags: docker
      notify: restart docker
      
    - name: Grant a user the ability to run containers
      user:
        name: appuser
        createhome: no
        groups: 
          - docker
        append: yes
      tags: docker

  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted
