- name: Configure and start gitlab-ci
  hosts: ci-server
  gather_facts: false
  become: true
  vars:
    public_ip: "{{ hostvars['ci-server'].gce_public_ip }}"

  tasks:
  - name: Creates all required directories
    file:
      path: "{{ item }}"
      state: directory
      mode: 0775
      recurse: yes
    with_items:
      - /srv/gitlab/config
      - /srv/gitlab/data
      - /srv/gitlab/logs
    tags: gitlab

  - name: Copy docker-compose for gitlab
    template:
      src: templates/docker-compose.yml.j2
      dest: /srv/gitlab/docker-compose.yml
      mode: 0775
    tags: gitlab

  - name: Run gitlab in container
    docker_service:
      project_src: /srv/gitlab/
      state: present
      restarted: yes
    tags: gitlab
